version: '3'
services:
  server:
    build:
      context: ./BackendDocker
    ports:
      - "4000:4000"
    # network_mode: host
    # networks:
    #   - comms
    volumes:
      - servervol:/app/serverdata

  client:
    build:
      context: ./FrontendDocker
    ports:
      - "5000:5000"
    # network_mode: host
    # networks:
    #   - comms
    volumes:
      - clientvol:/app/clientdata
    depends_on:
      - server

volumes:
  servervol:
  clientvol:

# networks:
#   comms:
#     driver: "host"