name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
    - completed

jobs:
  # build:
  deploy_container1:
    runs-on: [self-hosted,Linux,X64,BackendRunner]
    steps:
    - uses: actions/checkout@v3

    - name: Delete old Backend Docker image
      run: sudo rm -f dockerjuggy/my-capstone-backend:latest
    - name: Pull Backend Docker image
      run: sudo docker pull dockerjuggy/my-capstone-backend:latest
    - name: Deploy container on Backend Server
      run: sudo docker run -p 4000:4000 --name backend-container dockerjuggy/my-capstone-backend:latest
  
  deploy_container2:
    runs-on: [self-hosted,Linux,X64,FrontendRunner]
    steps:
    - uses: actions/checkout@v3

    - name: Delete old Frontend Docker image
      run: sudo rm -f dockerjuggy/my-capstone-frontend:latest
    - name: Pull Frontend Docker image
      run: sudo docker pull dockerjuggy/my-capstone-frontend:latest
    - name: Deploy container on Frontend Server
      run: sudo docker run -p 5000:5000 --name Frontend-container dockerjuggy/my-capstone-frontend:latest
      
