name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build Backend Docker Image
      # with:
      #   files: ./BackendDocker
      run: docker build -f ./BackendDocker/Dockerfile -t my-CapStone-Backend
    - name: Push Backend docker image to docker hub
      run: docker push dockerjuggy/my-Capstone-Backend:latest 
    - name: Build Frontend Docker Image
      run: docker build -f ./FrontendDocker/Dockerfile -t my-CapStone-Frontend
    - name: Push Frontend docker image to docker hub
      run: docker push dockerjuggy/my-Capstone-Frontend:latest
